# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
            scope: openid, profile, email, offline_access # last one for refresh tokens

jhipster:
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jhipsterOauth2SampleApplication
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    password:
